require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 3.2

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Naming/BlockForwarding:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  EnforcedStyle: brackets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "()"
    "%I": "()"
    "%r": "()"
    "%w": "()"
    "%W": "()"

Style/WordArray:
  EnforcedStyle: brackets
